name: environment_pnp
channels:
  - defaults
dependencies:
  - python=3.11
  - pip:
    - aiohttp==3.8.6
    - aiosignal==1.3.1
    - appdirs==1.4.4
    - asttokens==2.4.0
    - async-timeout==4.0.3
    - attrs==23.1.0
    - backcall==0.2.0
    - bm3d==4.0.1
    - bm4d==4.2.3
    - brotlipy==0.7.0
    - certifi==2023.7.22
    - cffi==1.15.1
    - charset-normalizer==2.0.4
    - click==8.1.7
    - cloudpickle==2.2.1
    - colorama==0.4.6
    - comm==0.1.4
    - contourpy==1.1.1
    - cryptography==41.0.3
    - cycler==0.12.1
    - debugpy==1.8.0
    - decorator==5.1.1
    - Deprecated==1.2.14
    - docker-pycreds==0.4.0
    - einops==0.7.0
    - executing==2.0.0
    - fastmri==0.3.0
    - filelock==3.9.0
    - fonttools==4.43.1
    - frozenlist==1.4.0
    - fsspec==2023.10.0
    - gitdb==4.0.11
    - GitPython==3.1.40
    - h5py==3.10.0
    - hdf5storage==0.1.19
    - huggingface-hub==0.18.0
    - idna==3.4
    - imageio==2.31.6
    - ipykernel==6.25.2
    - ipython==8.16.1
    - jedi==0.19.1
    - Jinja2==3.1.2
    - joblib==1.3.2
    - jupyter_client==8.3.1
    - jupyter_core==5.3.2
    - kiwisolver==1.4.5
    - kornia==0.7.0
    - lazy_loader==0.3
    - lightning-utilities==0.9.0
    - MarkupSafe==2.1.1
    - matplotlib==3.8.0
    - matplotlib-inline==0.1.6
    - mkl-fft==1.3.8
    - mkl-random==1.2.4
    - mkl-service==2.4.0
    - mpmath==1.3.0
    - multidict==6.0.4
    - nest-asyncio==1.5.8
    - networkx==3.1
    - numpy==1.26.0
    - packaging==23.2
    - pandas==2.1.2
    - parso==0.8.3
    - pathtools==0.1.2
    - pickleshare==0.7.5
    - Pillow==10.0.1
    - pip==23.2.1
    - platformdirs==3.11.0
    - plotly==5.18.0
    - pooch==1.7.0
    - prompt-toolkit==3.0.39
    - protobuf==4.25.0
    - psutil==5.9.5
    - pure-eval==0.2.2
    - pyarrow==14.0.0
    - pycparser==2.21
    - PyGithub==2.1.1
    - Pygments==2.16.1
    - PyJWT==2.8.0
    - PyNaCl==1.5.0
    - pyOpenSSL==23.2.0
    - pyparsing==3.1.1
    - PySocks==1.7.1
    - python-dateutil==2.8.2
    - pytorch-lightning==2.1.0
    - pytz==2023.3.post1
    - pyvista==0.42.3
    - PyWavelets==1.4.1
    - pywin32==306
    - PyYAML==6.0
    - pyzmq==25.1.1
    - requests==2.31.0
    - runstats==2.0.0
    - safetensors==0.4.0
    - scikit-image==0.22.0
    - scikit-learn==1.3.1
    - scipy==1.11.3
    - scooby==0.7.4
    - seaborn==0.13.0
    - sentry-sdk==1.34.0
    - setproctitle==1.3.3
    - setuptools==68.0.0
    - six==1.16.0
    - smmap==5.0.1
    - spyder-kernels==2.4.4
    - stack-data==0.6.3
    - sympy==1.11.1
    - tenacity==8.2.3
    - threadpoolctl==3.2.0
    - tifffile==2023.9.26
    - timm==0.9.8
    - torch==2.1.0
    - torch-cluster==1.6.2+pt21cu121
    - torch-geometric==2.3.1
    - torch-scatter==2.1.2+pt21cu121
    - torch-sparse==0.6.18
    - torch-spline-conv==1.2.2+pt21cu121
    - torchaudio==2.1.0
    - torchmetrics==1.2.0
    - torchvision==0.16.0
    - tornado==6.3.3
    - tqdm==4.66.1
    - traitlets==5.11.2
    - typing_extensions==4.7.1
    - tzdata==2023.3
    - urllib3==1.26.16
    - vtk==9.2.6
    - wandb==0.15.12
    - wcwidth==0.2.8
    - wheel==0.41.2
    - win-inet-pton==1.1.0
    - wrapt==1.15.0
    - yarl==1.9.2
